apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.secret }}
  {{ $key | b64enc }}: {{ $value | b64enc }}
{{- end }}